### ISSUE TITLE
Possible Bug with WHMCS 8.6.1

### ISSUE THREAD

**Issue by rzwebmaster** [PayGate/PayBatch_PayHost_WHMCS#10]
Hi Team,

I'm currently testing using WHMCS 8.6.1 with PHP 8.1 and encounter the following error when trying to use the payment gateway on checkout. Is there a fix/workaround for this?

`TypeError: array_key_exists(): Argument #2 ($array) must be of type array, stdClass given in /var/www/html/modules/gateways/payhostpaybatch.php:362
Stack trace:
#0 /var/www/html/modules/gateways/payhostpaybatch.php(72): payhostpaybatch_initiate()
#1 {main}`

**Comment by rackzar** [comment]
Hi Team,

Anyone monitoring this page?

**Comment by naasfourie** [comment]
Getting the same error.

**Comment by appinlet** [comment]
Hi @rzwebmaster and @naasfourie. 

Please note this is patched in release v1.0.8 https://github.com/PayGate/PayBatch_PayHost_WHMCS/releases/tag/v1.0.8
