### ISSUE TITLE
Updated Payment Gateway can't activate

### ISSUE THREAD

**Issue by naasfourie** [PayGate/PayBatch_PayHost_WHMCS#12]
Hi There.

The updated payment gateway on my side doesn't allow for activation, when clicking activate it just goes back to the previous screen and does not activate. Please advise.

Rgds

**Comment by appinlet** [comment]
@naasfourie this is strange. Please kindly raise this directly with the PayGate support team at [supportsa@dpogroup.com](mailto:supportsa@dpogroup.com) or reply to any active tickets and the team will assist ASAP.

**Comment by naasfourie** [comment]
[## 803589 ##] Fwd:Re: Re: issues with current release of 

Issue already raised more than a month ago, this was supposedly part and parcel of the same problem.

**Comment by appinlet** [comment]
Thanks @naasfourie; we have the ticket open and will continue on that thread. 

A response has been sent.

**Comment by appinlet** [comment]
Hi @naasfourie https://github.com/PayGate/PayBatch_PayHost_WHMCS/releases/tag/v1.0.9 addresses this issue. It is important to delete the old modules/addons/payhostpaybatch folder if this is on your server.

**Comment by naasfourie** [comment]
Thanks I can confirm everything is working perfectly!

Still to test the crons but I'm sure they'll be fine.
