### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by momedjussub** [PayGate/PayBatch_PayHost_WHMCS#2]
Hi!

This Payhost, when the costumer select on the invoice its redirect automatically to the paygate, if user back and open the invoice, once the invoice is open this will also redirect to the paygate, so if the user want change the payment method will be impossible because dont have time to see the invoice items or change the payment gateway, this is redirecting automatically

So you need put one button, the costumer need click on the button before redirect

Thanks

**Comment by RBAtkins0n** [comment]
Hi @momedjussub,

Please try 1.0.2 per #3, taking careful note of the new cron instructions.
If recurring is not required, kindly disable this option under.

**Comment by momedjussub** [comment]
Thank you

> Hi @momedjussub,
> 
> Please try v1.0.2 per #3, taking careful note of the new cron instructions (see PDF instructions under https://github.com/PayGate/PayBatch_PayHost_WHMCS/releases/tag/v1.0.2).
> If recurring is not required, kindly disable this option under settings.

Thank you very much

**Comment by momedjussub** [comment]
> Hi @momedjussub,
> 
> Please try v1.0.2 per #3, taking careful note of the new cron instructions (see PDF instructions under https://github.com/PayGate/PayBatch_PayHost_WHMCS/releases/tag/v1.0.2).
> If recurring is not required, kindly disable this option under settings.

I have updated but im facing same issue see this video 
https://streamable.com/kh9c7

**Comment by RBAtkins0n** [comment]
Thanks @momedjussub,

Looking into this.

**Comment by momedjussub** [comment]
> Thanks @momedjussub,
> 
> Looking into this.

Hi

Any update?

**Comment by RBAtkins0n** [comment]
Hi @momedjussub, 

Thank you for your patience, kindly v1.0.3 per #5.
